sudo: required
services:
  - docker

before_install:
  - docker build -t smithprince22/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true smithprince22/react-test npm test

after_success:
  - docker build -t smithprince22/multi-client ./client
  - docker build -t smithprince22/multi-nginx ./nginx
  - docker build -t smithprince22/mutli-server ./server
  - docker build -t smithprince22/mutli-worker ./worker
